spring:
  application:
    name: java-springboot-rest-api
    profiles:
      active: dev

jwt:
  secret: 1w2e3r4t5y6u7i8o9p0q1w2e3r4t5y6u7i8o9p0q1w2e3r4t5y6u7i8o9p0q1w2
  expirationMs: 7200000 # Expira em 2h
  refreshExpirationMs: 604800000 # Expira em 7 dias